name= input("enter ur name")
age= input("enter ur age")
city= input("enter ur city")
print("---NAME TAG---")
print("--------------")
print("name:",name)
print("age:",age)
print("city:",city)
print("loading", end="")
print(".", end="")
print(".", end="")
print(".")